name: Refresh all constant tables

on:
  push:
    branches:
      - master
  schedule:
    # Run every day at 12:00 JST
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate page
        run: python generate_chunithm.py