name: Refresh all constant tables

on:
  push:
    branches:
      - master
  schedule:
    # Run every day at 12:00 JST
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Generate page
        run: python generate_chunithm.py
      - name: Commit and push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Deploy: $(date -u)"
          git push origin master --force